version: "3"

services:
  quaerere-arangodb:
    image: "quaerereplatform/quaerere-arangodb:latest"
    ports:
      - "8529:8529"
    env_file:
      - ".env.arangodb"
    volumes:
      - "../../volumes/arangodb:/var/lib/arangodb3"
      - "../../volumes/arangodb-apps:/var/lib/arangodb3-apps"

  quaerere-redis:
    image: "redis:5.0-alpine"
    ports:
      - "6379:6379"

  quaerere-rabbitmq:
    image: "rabbitmq:3.7-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"

  willamette-api:
    image: "quaerereplatform/willamette:0.1.1"
    ports:
      - "5000:5000"
    depends_on:
      - quaerere-arangodb
    env_file:
      - ".env.willamette-api"
    environment:
      FLASK_APP: willamette.app:create_app
      WILLAMETTE_APP: api
      WILLAMETTE_URL_PREFIX: http://willamette-api:5000/api/

  columbia-api:
    build:
      context: "."
      args:
        develop: "true"
    ports:
      - "5001:5000"
    depends_on:
      - quaerere-arangodb
      - quaerere-rabbitmq
      - quaerere-redis
      - willamette-api
    env_file:
      - ".env.columbia-api"
    environment:
      COLUMBIA_APP: api
      COLUMBIA_URL_PREFIX: http://columbia-api:5000
      FLASK_APP: columbia.app:create_app
      WILLAMETTE_URL: http://willamette-api:5000/api/

  columbia-tasks:
    build:
      context: "."
      args:
        develop: "true"
    depends_on:
      - columbia-api
      - quaerere-arangodb
      - quaerere-rabbitmq
      - quaerere-redis
      - willamette-api
    env_file:
      - ".env.columbia-tasks"
    environment:
      ARANGODB_HOST: http://quaerere-arangodb:8529
      CELERY_BROKER_HOST: quaerere-rabbitmq
      CELERY_RESULT_HOST: quaerere-redis
      COLUMBIA_APP: tasks
      WILLAMETTE_URL: http://willamette-api:5000/api/

  columbia-scheduler:
    build:
      context: "."
      args:
        develop: "true"
    depends_on:
      - columbia-api
      - quaerere-arangodb
      - quaerere-rabbitmq
      - quaerere-redis
      - willamette-api
    env_file:
      - ".env.columbia-scheduler"
    environment:
      ARANGODB_HOST: http://quaerere-arangodb:8529
      CELERY_BROKER_HOST: quaerere-rabbitmq
      CELERY_RESULT_HOST: quaerere-redis
      COLUMBIA_APP: scheduler
